server:
  port: 8088

spring:
  config:
    import: optional:classpath:application-secret.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/mhfl_server
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    filter:
      order: -100
    jwt:
      key: ${JWT_KEY:abcdefghijk}
      expire: 7
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    username: ${MAIL_USERNAME:12345678@example.com}
    password: ${MAIL_PASSWORD:12345678}
  rabbitmq:
    addresses: localhost
    username: root
    password: 12345678
    virtual-host: /
  docker:
    compose:
      file: mhfl-server/compose.yaml

springdoc:
  swagger-ui:
    path: /doc/ui
  api-docs:
    path: /doc/json

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1, delete_time = NOW()
      logic-not-delete-value: 0
